version: 2.1

jobs:
  build:
    docker: 
      - image:  circleci/node:13.8.0
    steps:
      #brings repo with code to the current working directory of the docker environment
      - checkout
      #npm installs modules and their dependies into node_modules of docker envrionment
      - run:  npm i
      - run: npm run lint
  test:
    docker: 
      - image:  circleci/node:13.8.0
    steps:
      - checkout
      - run: npm i
      - run: npm run test
  analyze:
    docker: 
      - image:  circleci/node:13.8.0
    steps:
      - checkout
      - run: npm run audit
workflows:
  my_workflows:
    jobs:
      - build
      - test:
          requires:
            - buid
      - analyze:
          requires:
            - test